module.exports = (client) => {
  client.getArray = (name) => {
    const arrays = {
      gear: {
        all: [
          "Active Ace",
          "Boombox",
          "Bunch of Dice",
          "Chicken Stick",
          "Explode-o-matic Trigger",
          "Life Jacket",
          "Medicine Ball",
          "Monster Slugger",
          "Monster Taser",
          "Portable Portal",
          "R&B Mixtape",
          "Really Cool Sticker",
          "Shelldon",
          "Smart Fireworks",
          "Smelly Socks",
          "Snow Globe",
          "Spinsickle",
          "Techno Fists",
          "Turbo Pills",
          "Vampire Teeth",
          "Very Long Bow",
          "Water Balloon",
          "Wolf Stick",
          "Zap in a Box",
        ],
        active: [
          "Boombox",
          "Life Jacket",
          "Monster Taser",
          "Really Cool Sticker",
          "Shelldon",
          "Smart Fireworks",
          "Snow Globe",
          "Turbo Pills",
          "Water Balloon",
        ],
        passive: [
          "Active Ace",
          "Bunch of Dice",
          "Explode-o-matic Trigger",
          "R&B Mixtape",
          "Smelly Socks",
          "Vampire Teeth",
          "Zap in a Box",
        ],
        weapon: [
          "Chicken Stick",
          "Medicine Ball",
          "Monster Slugger",
          "Portable Portal",
          "Spinsickle",
          "Techno Fists",
          "Very Long Bow",
          "Wolf Stick",
        ],
      },

      drops: {
        all: [
          "Berserker Fist",
          "Bone Smasher Codpiece",
          "Boomer Tail",
          "Bronze Bell",
          "Charger Horn",
          "Executioner Axe",
          "Heavy Spitter Helmet",
          "Juggler Jewel",
          "Jumper Wing",
          "Knight Shoulderplate",
          "Lil Beetle Wing",
          "Lil Monster Scale",
          "Overlord Hood",
          "Papa Tooth",
          "Scorcher Fang",
          "Scrappy Scrap",
          "Slasher Blade",
          "Toxic Seed",
          "Champion Essence",
        ],
        standard: ["Lil Beetle Wing", "Lil Monster Scale"],
        elite: [
          "Boomer Tail",
          "Charger Horn",
          "Heavy Spitter Helmet",
          "Jumper Wing",
          "Knight Shoulderplate",
          "Scorcher Fang",
          "Scrappy Scrap",
          "Slasher Blade",
          "Toxic Seed",
        ],
        boss: [
          "Berserker Fist",
          "Bone Smasher Codpiece",
          "Bronze Bell",
          "Executioner Axe",
          "Juggler Jewel",
          "Overlord Hood",
          "Papa Tooth",
        ],
        champion: ["Champion Essence"],
      },

      monsters: {
        all: [
          "Lil Beetle",
          "Lil Grenadier",
          "Lil Grunt",
          "Lil Spitter",
          "Boomer",
          "Charger",
          "Heavy Spitter",
          "Jumper",
          "Knight",
          "Scavenger",
          "Scorcher",
          // "Scorcher Egg", not for spawning
          "Slasher",
          "Toxic Sapling",
          "Alarm Bell",
          "Big Papa",
          "Executioner",
          "Berserker",
          "Bone Smasher",
          "Juggler",
          "Overlord",
        ],
        standard: ["Lil Beetle", "Lil Grenadier", "Lil Grunt", "Lil Spitter"],
        elite: [
          "Boomer",
          "Charger",
          "Heavy Spitter",
          "Jumper",
          "Knight",
          "Scavenger",
          "Scorcher",
          // "Scorcher Egg", not for spawning
          "Slasher",
          "Toxic Sapling",
        ],
        boss: [
          "Alarm Bell",
          "Big Papa",
          "Executioner",
          "Berserker",
          "Bone Smasher",
          "Juggler",
          "Overlord",
        ],
        champion: [],
      },
    };

    return arrays[name];
  };
};
